name: Kris10x
favicon: null
layout_spectrum: 0.10651162988506258
typography_spectrum: 0.3395704380236566
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9757207343354821
  lightness: 0.20710562937892973
  saturation: 0.46938870707526803
  rhythmicContrast: 0.9582708822563291
purpose: []
